version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  bash:
    image: dbt-doctools-local
    command: ['bash']
    volumes:
      - .:/dbt-doctools


volumes:
  db:
    driver: local