version: '3.9'
services:
  init-db:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
    image: dbt-doctools:local
    depends_on:
      db:
        condition: service_healthy
    command: ['python', 'bin/init_db.py']
    volumes:
      - .:/dbt-doctools
    environment:
      - DBT_PROFILES_DIR=/dbt-doctools/dummy_dbt_project
      - DBT_DATABASE=dbt_doctools_test
      - PYTHONPATH=/dbt-doctools
